const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInSTock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Shirt',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p2.jpg',
      price: 80,
      countInSTock: 10,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 8,
      description: 'High Quality Pant',
    },
    {
      name: 'Nike Fat Pant',
      slug: 'Nike Fat Pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 110,
      countInSTock: 15,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 16,
      description: 'High Quality Pant',
    },
    {
      name: 'Nike Fat Pant',
      slug: 'Nike Fat Panty',
      category: 'Pants',
      image: '/images/p2.jpg',
      price: 130,
      countInSTock: 11,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 12,
      description: 'High Quality Pant',
    },
  ],
};

export default data;
